# Generated by Django 3.1.2 on 2020-11-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catenauser',
            name='access_token',
            field=models.TextField(null=True, verbose_name='Access Token'),
        ),
    ]
