# Generated by Django 3.1.2 on 2020-12-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201221_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='catenauser',
            name='description',
            field=models.TextField(default='', verbose_name='Profile Description'),
        ),
    ]
