# Generated by Django 3.1.2 on 2020-12-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_catenauser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='catenauser',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Refresh Token'),
        ),
        migrations.AlterField(
            model_name='catenauser',
            name='paipass_user_id',
            field=models.BigIntegerField(unique=True, verbose_name='Paipass User Id'),
        ),
    ]
