# Generated by Django 3.1.2 on 2020-12-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201221_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='catenauser',
            name='account_type',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Account Type'),
        ),
    ]
